### ISSUE TITLE
[PF2E] Handling Effect Values

### ISSUE THREAD

**Issue by harrisog** [Aedif/TokenVariants#114]
Some (but not all) conditions in the pf2e system have values appended (e.g., Sickened 2, Stunned 1). Currently the Effect Config requires an exact match, but It would be better to have the option to specify a range and/or wildcard operator

**Comment by Aedif** [comment]
https://github.com/Aedif/TokenVariants/releases/tag/4.42.0

in your two examples you can now type int he following:

- `Sickened \*` or `Sickened \{1,2,3,4\}`
- `Stunned \*` or `Stunned \{1,2,3,4\}`

**Comment by harrisog** [comment]
Updated to the latest version but I can't get this feature to work. Disabled mods, tested with both wildcard and ranges. I also noticed that compound expressions that were working previously (e.g., Blinded && \! Unconscious) are broken.

**Comment by Aedif** [comment]
Hmm just tested on PF2E and both `Blinded && \! Unconscious` and for example `Clumsy\*` work fine for me. 
What system and foundry versions are you on?

**Comment by Aedif** [comment]
Fixed the warning, but regarding the composite effects and wildcard effects not working; the issue was to do with overlays not rendering on v11, and PF2e rapidly applying multiple effects upon going Unconscious. Composites and wildcards themselves are working fine.

https://github.com/Aedif/TokenVariants/releases/tag/4.42.1

**Comment by harrisog** [comment]
Glad that the console error is gone, although unfortunately it does not seem to have fixed my issue. After some more time testing on my end I still cannot get either effect values or composite expressions to work in this version. 

I made a new world and successfully tested some single-element mapping expressions, but was not able to get the four examples in the attached json of exported global settings to work. For the sake of doing a quick eye test here, the changes being applied in this test are TMFX presets.

Afterward, I rolled back my installed version of TVA to 4.41.2 and the composite expressions worked again.
[not-working.json.zip](https://github.com/Aedif/TokenVariants/files/11770750/not-working.json.zip)

**Comment by Aedif** [comment]
Alright.. this took me down a bit of a rabbit hole.. PF2e does a lot of things slightly differently compared to DnD5e and as you can tell I don't test it as much.

Anyway... I fixed a number of bugs and all your example mappings should now work.

https://github.com/Aedif/TokenVariants/releases/tag/4.42.2

**Comment by harrisog** [comment]
That fixed it, thank you!
